[project]
name = "01-todo-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
]

[tool.uv.workspace]
members = ["by_streamlit"]
