api_key: null
cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      password: $2b$12$lhOfbg3eMo9/TIcgFOvlbuYTGJQBdTLU/ek3SiDOooJNrIktqfKr6
      roles:
        - admin
        - editor
        - viewer
    zbr:
      email: zubair@gmail.com
      first_name: Zubair
      last_name: Ahmed
      password: $2b$12$2x9pPxGcIUpnfDtRWP6AW.ftXlQuSpht8zsLOUIzRWWRTfHwaZYU2
      password_hint: zbr$12345
      roles: null
